version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - cd "./Auction Service"
      - sls deploy -s ${STAGE_NAME}
      - cd "../Authentication Service"
      - sls deploy -s ${STAGE_NAME}
      - cd "../Notification Service"
      - sls deploy -s ${STAGE_NAME}

cache:
  paths:
    - "Auction Service/node_modules"
    - "Authentication Service/node_modules"
    - "Notification Service/node_modules"
