service: auction-service

frameworkVersion: '2'

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, dev}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        method: GET
        path: /hello