service: auction-service

frameworkVersion: '2'

plugins:
  # - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  # test function
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello

  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

# custom variables that are not a part of the main sls framework
# this tells the serverless-bundle plugin to not perform linting
custom:
  bundle:
    linting: false