service: notification-service

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    name: notification-service-hello-${self:provider.stage}
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello