service: auction-service

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters # parameter references for aws stuff
  - serverless-offline

provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  environment: ${file(serverless.env.yml):${opt:stage, self:provider.stage}}
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    # - ${file(iam/MailQueueIAM.yml):MailQueueIAM}

# extra resources created using cloud formation
resources:
  Resources:
    # the specific resource's id - must be unique
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}


functions:
  # test function
  hello:
    name: hello-${opt:stage}
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
          authorizer: ${self:custom.authorizer}
          cors: true

  createAuction:
    name: createAuction-${opt:stage}
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          authorizer: ${self:custom.authorizer}
          cors: true

  getAuctions:
    name: getAuctions-${opt:stage}
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer: ${self:custom.authorizer}
          cors: true

  getAuction:
    name: getAuction-${opt:stage}
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          authorizer: ${self:custom.authorizer}
          cors: true

  placeBid:
    name: placeBid-${opt:stage}
    handler: src/handlers/placeBid.handler
    events:
      - http:
        # post used to create, patch to update an auction
          method: PATCH
          path: /auction/{id}/bid
          authorizer: ${self:custom.authorizer}
          cors: true

  processAuctions:
    name: processAuctions-${opt:stage}
    handler: src/handlers/processAuctions.handler
    # schedule an event to run every minute
    # events:
    #   - schedule: rate(1 minute)

# custom variables that are not a part of the main sls framework, we can define anything we want here
custom:
  # importing the cloud formation variables that were exported in notifications service
  authorizer: ${cf:authentication-service-${self:provider.stage}.AuthorizerArn}
  # MailQueue:
  #   arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
  #   url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}